<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1756273684317' stop='1756273686390'>
    <name>Motorola Calculator Tests</name>
    <title>Motorola Calculator Tests</title>
    <test-cases>
        <test-case start='1756273686332' status='broken' stop='1756273686390'>
            <name>"before all" hook for "should add 2 + 3 correctly"</name>
            <title>"before all" hook for "should add 2 + 3 correctly"</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>[quit()] Error response status: 9, UnknownCommand - The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource. Selenium error: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource</message>
                <stack-trace>Error: [quit()] Error response status: 9, UnknownCommand - The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource. Selenium error: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource
                    at exports.newError (node_modules\wd\lib\utils.js:152:13)
                    at PromiseWebdriver.&lt;anonymous> (node_modules\wd\lib\callbacks.js:36:19)
                    at cb (node_modules\wd\lib\webdriver.js:191:22)
                    at E:\Javascript\AppiumMochaFramework\node_modules\wd\lib\webdriver.js:205:5
                    at Request._callback (node_modules\wd\lib\http-utils.js:89:7)
                    at self.callback (node_modules\request\request.js:185:22)
                    at Request.emit (node:events:519:28)
                    at Request.&lt;anonymous> (node_modules\request\request.js:1161:10)
                    at Request.emit (node:events:519:28)
                    at IncomingMessage.&lt;anonymous> (node_modules\request\request.js:1083:12)
                    at Object.onceWrapper (node:events:633:28)
                    at IncomingMessage.emit (node:events:531:35)
                    at endReadableNT (node:internal/streams/readable:1696:12)
                    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>